language: python
branches:
  only:
  - master
  - /^ci-.*$/
matrix:
  include:
    # Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -U pip==18.0
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile
before_script:
  - make clean
script:
  # Full test suite, incl. coverage
  - make test
  - make check_pep8
  - make dead_code
after_script:
  - coveralls
