language: python
branches:
  only:
  - master
  - /^ci-.*$/
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -U pip
  - pip install pipenv
  - pipenv install --dev
script:
  # Full test suite, incl. coverage
  - pipenv run python -m coverage run --branch --source overtime_calculator --omit=overtime_calculator/setup.py -m py.test
after_success:
  - pipenv run python -m coverage report
